# Generated by Django 4.2.9 on 2024-01-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0003_topic_view_count_alter_topic_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
