# Generated by Django 4.2.9 on 2024-01-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0004_answer_update_date_alter_answer_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='writter',
            new_name='create_by',
        ),
    ]
