# Generated by Django 4.2.9 on 2024-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0005_rename_writter_answer_create_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
