# Generated by Django 5.0.1 on 2024-01-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0003_remove_answer_writter_alter_topic_last_updated_and_more'),
        ('boards1', '0006_remove_answer_create_by_remove_answer_update_date_and_more'),
    ]

    operations = [
    ]
